### ISSUE TITLE
Document 'Overview' is checked-in duplicated

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-log-upload#17]
## Describe the bug

The document 'Overview.md' is available at two different positions in the repo:
1) at doc/Overview.md
2) at src/doc/Overview.md

Note: This needs to be fixed **asap**.
The two versions are already out of synch.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix

Merge the two versions, and then delete one.

**Comment by Ein-Tim** [comment]
@f11h Could you please take a look at this? 🙂

**Comment by f11h** [comment]
I will check it tomorrow

**Comment by f11h** [comment]
I've create a PR for that. Thank you @ndegendogo !
