### ISSUE TITLE
CWA log upload is broken

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-log-upload#30]
## Describe the bug

Uploading logs from the app to the server fails with an error message. 

## Expected behaviour

Uploading an error log should be possible. 

## Steps to reproduce the issue

Differ between iOS & Android, should be clear.

## Possible Fix

@MikeMcC399 [found](https://github.com/corona-warn-app/cwa-app-android/issues/5089#issuecomment-1099483542) that https://logupload.coronawarn.app has a new SSL certificate issued today. Maybe this is the root cause? 

## Additional context

This issue was originally reported by @diablodale via https://github.com/corona-warn-app/cwa-app-android/issues/5089.

**Comment by Ein-Tim** [comment]
ping @thomasaugsten & @mlenkeit

**Comment by thomasaugsten** [comment]
The server team is working on this

**Comment by thomasaugsten** [comment]
Problem is solved

**Comment by diablodale** [comment]
And did the server team put in place monitoring and continuous testing of the live service so that it doesn't need a random end-user to report the problem?

**Comment by Ein-Tim** [comment]
Also, it would be interesting to know what the cause of this issue was and what is done to prevent it from re-occurring.
